apiVersion: v1
kind: Service
metadata:
  name: nginx_service
  labels:
    app: nginx_service
spec:
  type: NodePort
  selector:
    matchLabels:
      app: nginx_pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: NodePort
