apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  ports:
  - port: 8094
    targetPort: 8094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf-image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
#        env:
#          - name: USER
#            value: "fflores"
#          - name: INFLUX_PASSWORD
#            value: "fflores"
#          - name: INFLUX_URL
#            value: "http://influxdb-service:8086"
        ports:
        - containerPort: 8094

