apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-image
        imagePullPolicy: Never
        env:
            - name: GF_SECURITY_ADMIN_USER
              value: "fflores"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "fflores"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ip
  name: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    
