apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 6000
        - containerPort: 6001
        - containerPort: 6002
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ip
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: p21
  - port: 20
    targetPort: 20
    name: p20
  - port: 6000
    targetPort: 6000
    name: p6000
  - port: 6001
    targetPort: 6001
    name: p6001 
  - port: 6002
    targetPort: 6002
    name: p6002